# Generated by Django 3.0.7 on 2020-06-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200613_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
